version: '3.7'

services:
  flask:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - memcached
    environment:
      - PORT=8081
    links:
      - memcached
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"